version: "3.8"
services:
  mysql_realestate:
    image: mysql:8.0
    container_name: mysql_realestate
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: realestate
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Jakarta
    ports:
      - "3307:3306"   # gunakan port host 3307 agar tidak bentrok dgn MySQL lokal
    volumes:
      - db_realestate_app_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: btc_user_service
    ports:
      - "8081:8081"
    networks:
      - btc-net
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql_realestate:
        condition: service_healthy

  listing-service:
    build:
      context: ./listing-service
      dockerfile: Dockerfile
    container_name: btc_listing_service
    ports:
      - "6000:6000"
    networks:
      - btc-net
    depends_on:
      mysql_realestate:
        condition: service_healthy

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: btc_api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - listing-service
      - mysql_realestate
    networks:
      - btc-net

networks:
  btc-net:
    driver: bridge

volumes:
  db_realestate_app_data:
