server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false

      default-filters:
        - RemoveHopByHopHeaders=connection,keep-alive,transfer-encoding,proxy-authenticate,proxy-authorization,te,trailers

      routes:

        # ========== USER SERVICE ==========
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**
            - Path=/api/user/**
          filters:
            - StripPrefix=0

        # ========== LISTING SERVICE ==========
        - id: listing-service
          uri: http://listing-service:6000
          predicates:
            - Path=/listings/**
            - Path=/ping/**
          filters:
            - StripPrefix=0
