spring:
  cloud:
    gateway:
      routes:
        # USER SERVICE
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**, /api/user/**
          filters:
            - StripPrefix=0

        # LISTING SERVICE
        - id: listing-service
          uri: http://listing-service:6000
          predicates:
            - Path=/listings/**, /ping/**
          filters:
            - StripPrefix=0

        # PUBLIC USER SERVICE
        - id: public-users
          uri: http://user-service:8081
          predicates:
            - Path=/public-api/users/**
          filters:
            - StripPrefix=1

        # PUBLIC LISTING SERVICE
        - id: public-listings
          uri: http://listing-service:6000
          predicates:
            - Path=/public-api/listings/**
          filters:
            - StripPrefix=1
