version: '3.8'

services:
  mysql_realestate:
    image: mysql:8.0
    container_name: mysql_realestate
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: realestate
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Jakarta
    ports:
      - "3307:3306"   # gunakan port host 3307 agar tidak bentrok dgn MySQL lokal
    volumes:
      - db_realestate_app_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring_realestate_app:
    build: .
    container_name: spring_realestate_app
    depends_on:
      mysql_realestate:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_realestate:3306/realestate?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&serverTimezone=Asia/Jakarta
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      TZ: Asia/Jakarta
    ports:
      - "8081:8081"
    # Tambahkan sedikit delay agar MySQL benar-benar siap
    command: sh -c "sleep 10 && java -jar app.jar"

volumes:
  db_realestate_app_data:
